// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231011152818_create")]
    partial class create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("app.Models.Code", b =>
                {
                    b.Property<long>("idSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idSystem"), 1L, 1);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSystem");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("app.Models.Grade", b =>
                {
                    b.Property<long>("idSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("idSystem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idSystem"), 1L, 1);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSystem");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("app.Models.Student", b =>
                {
                    b.Property<long>("idSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idSystem"), 1L, 1);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("studentCode")
                        .HasColumnType("bigint");

                    b.Property<long?>("studentGrade")
                        .HasColumnType("bigint");

                    b.HasKey("idSystem");

                    b.HasIndex("studentCode");

                    b.HasIndex("studentGrade");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("app.Models.User", b =>
                {
                    b.Property<long>("IdSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Idsystem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSystem"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.HasKey("IdSystem");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("app.Models.Student", b =>
                {
                    b.HasOne("app.Models.Code", "Code")
                        .WithMany()
                        .HasForeignKey("studentCode");

                    b.HasOne("app.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("studentGrade");

                    b.Navigation("Code");

                    b.Navigation("Grade");
                });
#pragma warning restore 612, 618
        }
    }
}
